# Generated by Django 4.2.3 on 2023-08-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('degree', models.CharField(max_length=300)),
                ('specialization', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
